import pg from './pg.png'
import Image from 'next/image'
import mysql from './mysql.png'
import groq from './groq.png'
import Ggroq from './Ggroq.png'
import gemma from './gemma.png'
import g from './g.png'
import metaAI from './metaAI.jpeg'
import meta from './meta.jpeg'
import mongo from './mongo.png'
import metaAI2 from './Meta-ai-logo.png'
import mongodbhigh from './mongodbhigh.png'
import mongoDB from './mongoDB.png'
import oracleDB from './oracledb.png'
import oracle from './oracle.png'
import neonDB from './neonDB.png'
import mixtral from './mixtral.png'

export { pg, mysql, groq, Ggroq, gemma, g, metaAI, meta, mongo, metaAI2, mongodbhigh, mongoDB, oracleDB, oracle, neonDB, mixtral }