import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans", });

export const metadata = {
  title: "Quersage",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={
        cn("min-h-screen bg-background font-sans antialiased", inter.variable)
      }>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >{children}
        </ThemeProvider>
      </body>
    </html>
  );
}
